prompt --application/deployment/install/install_crear_objetos
begin
--   Manifest
--     INSTALL: INSTALL-Crear objetos
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>26293853277175009384
,p_default_application_id=>95395
,p_default_id_offset=>46234255895120286976
,p_default_owner=>'SOLID192'
);
wwv_flow_api.create_install_script(
 p_id=>wwv_flow_api.id(26676731926547005881)
,p_install_id=>wwv_flow_api.id(26676731700493001573)
,p_name=>'Crear objetos'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'CREATE TABLE  "COR_USER" ',
'   (	"ID" NUMBER(20,0), ',
'	"USER_SEX" VARCHAR2(20), ',
'	"USER_APELLIDO" VARCHAR2(20), ',
'	"USER_NOMBRE" VARCHAR2(50), ',
'	"USER_DEPT" VARCHAR2(50), ',
'	"USER_PROV" VARCHAR2(50), ',
'	"USER_DISTR" VARCHAR2(50), ',
'	"USER_CPOSTAL" VARCHAR2(10), ',
'	"USER_TLF" VARCHAR2(20), ',
'	"USER_LOCACION" VARCHAR2(500), ',
'	"LAT" VARCHAR2(20), ',
'	"LNG" VARCHAR2(20), ',
'	"USER_EMAIL" VARCHAR2(50), ',
'	"USER_EMAIL_CHECK" VARCHAR2(50), ',
'	"USER_CONTRA" VARCHAR2(20), ',
'	"USER_PRIV" VARCHAR2(5), ',
'	"ADMIN" VARCHAR2(10), ',
'	 CONSTRAINT "COR_USER_PK" PRIMARY KEY ("ID")',
'  USING INDEX  ENABLE',
'   )',
'/',
'CREATE TABLE  "COR_POST" ',
'   (	"ID" NUMBER NOT NULL ENABLE, ',
'	"POST_TITULO" VARCHAR2(500) NOT NULL ENABLE, ',
'	"POST_DESCR" VARCHAR2(500), ',
'	"POST_CATEGORIA" VARCHAR2(100), ',
'	"POST_LINK" VARCHAR2(35), ',
'	"POST_FREG" DATE, ',
'	"POST_FCAD" DATE, ',
'	"POST_PRIV" VARCHAR2(5), ',
'	"POST_USER" NUMBER NOT NULL ENABLE, ',
'	"POST_TIPO" VARCHAR2(10) NOT NULL ENABLE, ',
'	 CONSTRAINT "COR_POST_PK" PRIMARY KEY ("ID")',
'  USING INDEX  ENABLE',
'   )',
'/',
'CREATE TABLE  "COR_MSG" ',
'   (	"ID" NUMBER NOT NULL ENABLE, ',
'	"MSG_MENSAJE" VARCHAR2(500), ',
'	"MSG_POST" NUMBER NOT NULL ENABLE, ',
'	"MSG_USER" NUMBER NOT NULL ENABLE, ',
'	 CONSTRAINT "COR_MSG_PK" PRIMARY KEY ("ID")',
'  USING INDEX  ENABLE',
'   )',
'/',
'CREATE TABLE  "HTMLDB_PLAN_TABLE" ',
'   (	"STATEMENT_ID" VARCHAR2(30), ',
'	"PLAN_ID" NUMBER, ',
'	"TIMESTAMP" DATE, ',
'	"REMARKS" VARCHAR2(4000), ',
'	"OPERATION" VARCHAR2(30), ',
'	"OPTIONS" VARCHAR2(255), ',
'	"OBJECT_NODE" VARCHAR2(128), ',
'	"OBJECT_OWNER" VARCHAR2(128), ',
'	"OBJECT_NAME" VARCHAR2(128), ',
'	"OBJECT_ALIAS" VARCHAR2(261), ',
'	"OBJECT_INSTANCE" NUMBER(*,0), ',
'	"OBJECT_TYPE" VARCHAR2(128), ',
'	"OPTIMIZER" VARCHAR2(255), ',
'	"SEARCH_COLUMNS" NUMBER, ',
'	"ID" NUMBER(*,0), ',
'	"PARENT_ID" NUMBER(*,0), ',
'	"DEPTH" NUMBER(*,0), ',
'	"POSITION" NUMBER(*,0), ',
'	"COST" NUMBER(*,0), ',
'	"CARDINALITY" NUMBER(*,0), ',
'	"BYTES" NUMBER(*,0), ',
'	"OTHER_TAG" VARCHAR2(255), ',
'	"PARTITION_START" VARCHAR2(255), ',
'	"PARTITION_STOP" VARCHAR2(255), ',
'	"PARTITION_ID" NUMBER(*,0), ',
'	"OTHER" LONG, ',
'	"DISTRIBUTION" VARCHAR2(30), ',
'	"CPU_COST" NUMBER(*,0), ',
'	"IO_COST" NUMBER(*,0), ',
'	"TEMP_SPACE" NUMBER(*,0), ',
'	"ACCESS_PREDICATES" VARCHAR2(4000), ',
'	"FILTER_PREDICATES" VARCHAR2(4000), ',
'	"PROJECTION" VARCHAR2(4000), ',
'	"TIME" NUMBER(*,0), ',
'	"QBLOCK_NAME" VARCHAR2(128)',
'   )',
'/',
'CREATE TABLE  "COR_CATEGORIES" ',
'   (	"CAT_ID" NUMBER NOT NULL ENABLE, ',
'	"NOMBRE" VARCHAR2(30), ',
'	"CAT_NOM_ENG" VARCHAR2(30), ',
'	 CONSTRAINT "COR_CATEGORIES_PK" PRIMARY KEY ("CAT_ID")',
'  USING INDEX  ENABLE',
'   )',
'/',
'ALTER TABLE  "COR_MSG" ADD CONSTRAINT "COR_MSG_POST_FK" FOREIGN KEY ("MSG_POST")',
'	  REFERENCES  "COR_POST" ("ID") ENABLE',
'/',
'ALTER TABLE  "COR_MSG" ADD CONSTRAINT "COR_MSG_USER_FK" FOREIGN KEY ("MSG_USER")',
'	  REFERENCES  "COR_USER" ("ID") ENABLE',
'/',
'ALTER TABLE  "COR_POST" ADD CONSTRAINT "COR_POST_USER_FK" FOREIGN KEY ("POST_USER")',
'	  REFERENCES  "COR_USER" ("ID") ENABLE',
'/',
'CREATE OR REPLACE EDITIONABLE FUNCTION  "CORONA_AUTH_FUNCTION" ',
'(p_username in varchar2, p_password in varchar2)',
'RETURN BOOLEAN',
'AS',
'BEGIN',
'for c1 in (select 1 from COR_USER where upper(USER_EMAIL) = upper(p_username) and USER_CONTRA = p_password ) loop',
'return true;',
'end loop;',
'return false;',
'end;',
'/',
'',
'CREATE UNIQUE INDEX  "COR_CATEGORIES_PK" ON  "COR_CATEGORIES" ("CAT_ID")',
'/',
'CREATE UNIQUE INDEX  "COR_MSG_PK" ON  "COR_MSG" ("ID")',
'/',
'CREATE UNIQUE INDEX  "COR_POST_PK" ON  "COR_POST" ("ID")',
'/',
'CREATE UNIQUE INDEX  "COR_USER_PK" ON  "COR_USER" ("ID")',
'/',
' CREATE SEQUENCE   "COR_CATEGORIES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL',
'/',
' CREATE SEQUENCE   "COR_MSG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 481 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL',
'/',
' CREATE SEQUENCE   "COR_POST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 641 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL',
'/',
' CREATE SEQUENCE   "COR_USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 541 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL',
'/',
'CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_COR_CATEGORIES" ',
'  before insert on "COR_CATEGORIES"               ',
'  for each row  ',
'begin   ',
'  if :NEW."CAT_ID" is null then ',
'    select "COR_CATEGORIES_SEQ".nextval into :NEW."CAT_ID" from sys.dual; ',
'  end if; ',
'end;',
'',
'/',
'ALTER TRIGGER  "BI_COR_CATEGORIES" ENABLE',
'/',
'CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_COR_MSG" ',
'  before insert on "COR_MSG"               ',
'  for each row  ',
'begin   ',
'  if :NEW."ID" is null then ',
'    select "COR_MSG_SEQ".nextval into :NEW."ID" from sys.dual; ',
'  end if; ',
'end;',
'',
'/',
'ALTER TRIGGER  "BI_COR_MSG" ENABLE',
'/',
'CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_COR_POST" ',
'  before insert on "COR_POST"               ',
'  for each row  ',
'begin   ',
'  if :NEW."ID" is null then ',
'    select "COR_POST_SEQ".nextval into :NEW."ID" from sys.dual; ',
'  end if; ',
'end;',
'',
'/',
'ALTER TRIGGER  "BI_COR_POST" ENABLE',
'/',
'CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_COR_USER" ',
'  before insert on "COR_USER"               ',
'  for each row  ',
'begin   ',
'  if :NEW."ID" is null then ',
'    select "COR_USER_SEQ".nextval into :NEW."ID" from sys.dual; ',
'  end if; ',
'end;',
'',
'/',
'ALTER TRIGGER  "BI_COR_USER" ENABLE',
'/'))
);
wwv_flow_api.component_end;
end;
/
